name: Build Feature Branch on PR

on:
  pull_request:
    types:
      - opened

env:
  NODE_VERSION: latest

jobs:
  build:
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # setup node
      - name: Setup node
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"
      - run: bun install
      - run: bun run build
